# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "SPEftoYxVq9X5sLEdVeosuLFUdXBuWOQ1f3k761BxQ6tuFbbLvu5lqSP5TDvMu0VIbiWZwAs1gYLiHJGDkeIm/d4+DssdQIMf1fgw08S/gF4opkZimj48Uxwgi8eog1NIgqLJvpXFiBrH+RpPml0HwR4uBltQNfjnHX27V6TsRCrsm+HoQDM2Sb7JUPl3Y8EuaOhUyj+qP+2XTC3boZxghQuxIgXJz8HiWYzDppmXt9AyeH/oxOt/fSvRKhAdv40vYzC6xB2AZjeNwdjgWUpeGPTQftY1a7c02wZzZZqylamaMSzVOTxAUNkTIwL+vZt0ihNf8+NFsBCKv7Vv23fj/jhUNRbwOfsmQkBV39Y2+4BHhU6OZEFf3FVn7ky5bUrhhF8EX9Us1zS4yZcxqwaO2CT/Y9C6hmaw1V/X88vX7WDF6HwtgN9Bcwlfn5xvCJa7u1zpWgTF/I9NoWrTnac+xI3kCJCc3NAviBcY/BzJpDjouK+T2icg8L4hhPxjH3wMofA1pNhSpN+SpPzfyZSB7+H6hCYI7gKbBwxDFsaoJ1JrP37dPCEFaLJ33FxCg61P/NALtG1Th20a80afQ/AhvzFPFZFRUxzJ2X4INp3li8pKIxLzjTmFwovoOh7vBLpJdKMWs3wOcEvJR0kjOfT+1RaUJjaJOZYtDfDt+oIJ94="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
