travis:
  secure:
    BINSTAR_TOKEN: vNXN9ZKu+GR28E8dNsD6g6bBq9vDzn/GEeRBXYTGkVRJAwRmdWgtYA0xKLehbMV86gvJrS9odhQiLynNEKFkApic5crxZlqdI2Hvx0Wlem4PQkxunsr92Pgc/wbsky+BgA0SMfp71LiyFgKWgPIMSDchVdafYgNNUp6pRFbLMIiW6A6KlXrwdMGrG4vT3XFrF/S+vxnxzLz9zCw4KpEsUod+QqrOnbsFIdaQvMOxkYBbBCb3cCEhU1kysgnAhCaHt30lw9UTwEz67i+0eXhgs2AIWk2aSeoDDQHuPv0mt5SRWtGbU4uTYbaUSNVg6AU81TPamn+rAMO9UslvkvZe1O6M5Fx4SNDYoBsOHj4gjTNVwL+5jRgFt5Q6cZhtZv+hxKXhGfaaf0nHv5YVjdMlr3OTlDdwpol2UUtOW2rDJEr5FERYrUr1VHzuyLTwXFLfeFVya+zBUsABTgNVFuIz1XZGTzdXIH5RrZopkd0ItRdxEq1XOp9FCc1f3ZTyQfXBDmHvL0WjC0qH0ccKXJmXisv8dpRztqKWavgt5qHLBex+V6/2ky7/PMbtEZSlXPdeQkKnCI3aBd3iEh7fLSHufTtaOOMoqb0zdC0Xx0SP4Sl7e4tCitG1MvmZgN88NrXkH7JFxwULXNVBoluFRcINtq0he2JXdJ3H2J5m2SoNElw=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
