travis:
  secure:
    BINSTAR_TOKEN: SPEftoYxVq9X5sLEdVeosuLFUdXBuWOQ1f3k761BxQ6tuFbbLvu5lqSP5TDvMu0VIbiWZwAs1gYLiHJGDkeIm/d4+DssdQIMf1fgw08S/gF4opkZimj48Uxwgi8eog1NIgqLJvpXFiBrH+RpPml0HwR4uBltQNfjnHX27V6TsRCrsm+HoQDM2Sb7JUPl3Y8EuaOhUyj+qP+2XTC3boZxghQuxIgXJz8HiWYzDppmXt9AyeH/oxOt/fSvRKhAdv40vYzC6xB2AZjeNwdjgWUpeGPTQftY1a7c02wZzZZqylamaMSzVOTxAUNkTIwL+vZt0ihNf8+NFsBCKv7Vv23fj/jhUNRbwOfsmQkBV39Y2+4BHhU6OZEFf3FVn7ky5bUrhhF8EX9Us1zS4yZcxqwaO2CT/Y9C6hmaw1V/X88vX7WDF6HwtgN9Bcwlfn5xvCJa7u1zpWgTF/I9NoWrTnac+xI3kCJCc3NAviBcY/BzJpDjouK+T2icg8L4hhPxjH3wMofA1pNhSpN+SpPzfyZSB7+H6hCYI7gKbBwxDFsaoJ1JrP37dPCEFaLJ33FxCg61P/NALtG1Th20a80afQ/AhvzFPFZFRUxzJ2X4INp3li8pKIxLzjTmFwovoOh7vBLpJdKMWs3wOcEvJR0kjOfT+1RaUJjaJOZYtDfDt+oIJ94=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
